name: Run FINMIND Token Test

on:
  workflow_dispatch:

jobs:
  run-token:
    runs-on: ubuntu-latest

    env:
      FINMIND_TOKEN: ${{ secrets.FINMIND_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run script
        run: python FINMINDToken.py